export enum AnalyticEventType {
  DISPLAY_EVENT = 'DISPLAY_EVENT',
  CHANGE_EVENT = 'CHANGE_EVENT',
  CLICK_EVENT = 'CLICK_EVENT',
  PAGE_VIEW_EVENT = 'PAGE_VIEW_EVENT',
  API_START_EVENT = 'API_START_EVENT',
  API_COMPLETE_EVENT = 'API_COMPLETE_EVENT',
}
